apiVersion: 1

datasources:
  # ── Loki ───────────────────────────────────────────────────────────────────
  # Datasource pré-provisionado para ler logs coletados pelo Promtail.
  - name: Loki
    type: loki
    access: proxy
    url: http://tcc-loki:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
